name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new action trigger
        env:
          GH_OWNER: ${{ secrets.GH_OWNER }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Trigger action:"
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$GH_OWNER/$GH_REPO/actions/workflows/pull-and-replace.yml/dispatches \
            -d '{"ref":"main"}'